### ISSUE TITLE
how to create About-Me page

### ISSUE THREAD

**Issue by zydarChen** [varunchandak/blog#1]
hi, I'm trying to using clean-blog to bulit my own blog. And I viewed your answers about the About-Me page. 
Can you give more details about how to solve it? How can I rewrite the about.ejs?

**Comment by varunchandak** [comment]
if you check my blog's about-me.ejs under layout and about-me page under source, then you can understand.

In short, create an ejs under layout and specify that filename in **layout: <FILENAME>** in the .md file under source.

**Comment by zydarChen** [comment]
But how can I find your about-me.ejs?

**Comment by varunchandak** [comment]
**cat source/About-Me/index.md**

> ---
> title: About Me
> subtitle: whoami
> comments: false
> layout: About-Me
> ---

**cat themes/clean-blog/layout/About-Me.ejs**

> 
> 
> <header class="intro-header" style="background-image: url('<%- theme.index_cover %>')">
>     <div class="container">
>         <div class="row">
>             <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
>                 <div class="site-heading">
>                     <h1>About Me</h1>
>                     <hr class="small">
>                     <span class="subheading">whoami</span>
>                 </div>
>             </div>
>         </div>
>     </div>
> </header>

**Comment by zydarChen** [comment]
Great! Thank you so much! That really helps me a lot.
I rewrite your .ejs, and now it can change the title, subtitle, cover and can display the Content.

```
<!-- Page Header -->
<!-- Set your background image for this header in your post front-matter: cover -->
<%
    var cover = page.cover || theme.index_cover;
%>
<header class="intro-header" style="background-image: url('<%- cover %>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1><%- page.title %></h1>
                    <hr class="small">
                    <span class="subheading"><%- page.subtitle %></span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <!-- Post Main Content -->
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <%- page.content %>
            </div>
        </div>
    </div>
</article>
```
